name: ci

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Using Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint:check

      - name: Run Tests
        run: npm test

      - name: Generate coverage report in Pull Request Comments
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ github.token }}
